

services:
  - type: web
    name: intranet-djogana
    runtime: node
    buildCommand: npm run render:build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "22"
